name: tuvi_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.5 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  expressions: ^0.2.5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  sunoom:
    path: ../sunoom
