final basicStarInfo = {
  "tuVi": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "binh",
      1: "dac",
      2: "mieu",
      3: "binh",
      4: "vuong",
      5: "mieu",
      6: "mieu",
      7: "dac",
      8: "mieu",
      9: "binh",
      10: "vuong",
      11: "binh",
    },
    "nguHanh": "duong_tho"
  },
  "liemTrinh": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "vuong",
      1: "dac",
      2: "vuong",
      3: "ham",
      4: "mieu",
      5: "ham",
      6: "vuong",
      7: "dac",
      8: "vuong",
      9: "ham",
      10: "mieu",
      11: "ham",
    },
    "nguHanh": "am_hoa"
  },
  "thienDong": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "vuong",
      1: "ham",
      2: "mieu",
      3: "dac",
      4: "ham",
      5: "ham",
      6: "dac",
      7: "ham",
      8: "mieu",
      9: "ham",
      10: "ham",
      11: "dac",
    },
    "nguHanh": "duong_thuy"
  },
  "vuKhuc": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "vuong",
      1: "mieu",
      2: "vuong",
      3: "dac",
      4: "mieu",
      5: "ham",
      6: "vuong",
      7: "mieu",
      8: "vuong",
      9: "dac",
      10: "mieu",
      11: "ham",
    },
    "nguHanh": "am_kim"
  },
  "thaiDuong": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "ham",
      1: "dac",
      2: "vuong",
      3: "vuong",
      4: "vuong",
      5: "mieu",
      6: "mieu",
      7: "dac",
      8: "ham",
      9: "ham",
      10: "ham",
      11: "ham",
    },
    "nguHanh": "duong_hoa"
  },
  "thienCo": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "dac",
      1: "dac",
      2: "ham",
      3: "mieu",
      4: "mieu",
      5: "vuong",
      6: "dac",
      7: "dac",
      8: "vuong",
      9: "mieu",
      10: "mieu",
      11: "ham",
    },
    "nguHanh": "am_moc"
  },
  "thienPhu": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "mieu",
      1: "binh",
      2: "mieu",
      3: "binh",
      4: "vuong",
      5: "dac",
      6: "mieu",
      7: "dac",
      8: "mieu",
      9: "binh",
      10: "vuong",
      11: "dac",
    },
    "nguHanh": "am_tho"
  },
  "thaiAm": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "vuong",
      1: "dac",
      2: "ham",
      3: "ham",
      4: "ham",
      5: "ham",
      6: "ham",
      7: "dac",
      8: "vuong",
      9: "mieu",
      10: "mieu",
      11: "mieu",
    },
    "nguHanh": "am_thuy"
  },
  "thamLang": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "ham",
      1: "mieu",
      2: "dac",
      3: "ham",
      4: "vuong",
      5: "ham",
      6: "ham",
      7: "mieu",
      8: "dac",
      9: "ham",
      10: "vuong",
      11: "ham",
    },
    "nguHanh": "moc"
  },
  "cuMon": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "vuong",
      1: "ham",
      2: "vuong",
      3: "mieu",
      4: "ham",
      5: "ham",
      6: "vuong",
      7: "ham",
      8: "dac",
      9: "mieu",
      10: "ham",
      11: "dac",
    },
    "nguHanh": "am_thuy"
  },
  "thienTuong": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "vuong",
      1: "dac",
      2: "mieu",
      3: "ham",
      4: "vuong",
      5: "dac",
      6: "vuong",
      7: "dac",
      8: "mieu",
      9: "ham",
      10: "vuong",
      11: "dac",
    },
    "nguHanh": "duong_thuy"
  },
  "thienLuong": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "vuong",
      1: "dac",
      2: "vuong",
      3: "vuong",
      4: "mieu",
      5: "ham",
      6: "mieu",
      7: "dac",
      8: "vuong",
      9: "ham",
      10: "mieu",
      11: "ham",
    },
    "nguHanh": "am_moc"
  },
  "thatSat": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "mieu",
      1: "dac",
      2: "mieu",
      3: "ham",
      4: "ham",
      5: "vuong",
      6: "mieu",
      7: "dac",
      8: "mieu",
      9: "ham",
      10: "ham",
      11: "vuong",
    },
    "nguHanh": "duong_kim"
  },
  "phaQuan": {
    "isMajor": true,
    "bold": true,
    "strengths": {
      0: "mieu",
      1: "vuong",
      2: "ham",
      3: "ham",
      4: "dac",
      5: "ham",
      6: "mieu",
      7: "vuong",
      8: "ham",
      9: "ham",
      10: "dac",
      11: "ham",
    },
    "nguHanh": "am_thuy"
  },
  "locTon": {
    "isGood": true,
    "bold": true,
    "nguHanh": "duong_thoDoiThuy",
  },
  "kinhDuong": {
    "bold": true,
    "isKiller": true,
    "strengths": {
      0: "",
      1: "dac",
      2: "",
      3: "",
      4: "dac",
      5: "",
      6: "",
      7: "dac",
      8: "",
      9: "",
      10: "dac",
      11: "",
    },
    "nguHanh": "am_kimDoiHoa"
  },
  "daLa": {
    "bold": true,
    "isKiller": true,
    "strengths": {
      0: "",
      1: "dac",
      2: "",
      3: "",
      4: "dac",
      5: "",
      6: "",
      7: "dac",
      8: "",
      9: "",
      10: "dac",
      11: "",
    },
    "nguHanh": "am_kimDoiHoa"
  },
  "hoaTinh": {
    "bold": true,
    "isKiller": true,
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "dac",
      5: "dac",
      6: "dac",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "am_hoa"
  },
  "linhTinh": {
    "bold": true,
    "isKiller": true,
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "dac",
      5: "dac",
      6: "dac",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "am_hoa"
  },
  "vanXuong": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "dac",
      2: "",
      3: "",
      4: "dac",
      5: "dac",
      6: "",
      7: "dac",
      8: "",
      9: "",
      10: "dac",
      11: "dac",
    },
    "nguHanh": "duong_kimDoiTho"
  },
  "vanKhuc": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "dac",
      2: "",
      3: "",
      4: "dac",
      5: "dac",
      6: "",
      7: "dac",
      8: "",
      9: "",
      10: "dac",
      11: "dac",
    },
    "nguHanh": "duong_thuyDoiHoa"
  },
  "thienKhoi": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "duong_hoaDoiKim"
  },
  "thienViet": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "am_hoaDoiMoc"
  },
  "taPhu": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "duong_thoDoiKim"
  },
  "huuBat": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "duong_thuyDoiTho"
  },
  "diaKiep": {
    "bold": true,
    "isKiller": true,
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "",
      4: "",
      5: "dac",
      6: "",
      7: "",
      8: "dac",
      9: "",
      10: "",
      11: "dac",
    },
    "nguHanh": "hoa"
  },
  "diaKhong": {
    "bold": true,
    "isKiller": true,
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "",
      4: "",
      5: "dac",
      6: "",
      7: "",
      8: "dac",
      9: "",
      10: "",
      11: "dac",
    },
    "nguHanh": "hoa"
  },
  "thienKhong": {"bold": true, "nguHanh": "hoa"},
  "hoaLoc": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "mocDoiTho"
  },
  "hoaQuyen": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "mocDoiThuy"
  },
  "hoaKhoa": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "mocDoiThuy"
  },
  "hoaKy": {
    "bold": true,
    "strengths": {
      0: "",
      1: "dac",
      2: "",
      3: "",
      4: "dac",
      5: "",
      6: "",
      7: "dac",
      8: "",
      9: "",
      10: "dac",
      11: "",
    },
    "nguHanh": "thuy"
  },
  "daiHao": {
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "dac",
      9: "dac",
      10: "",
      11: "",
    },
    "nguHanh": "hoa"
  },
  "tieuHao": {
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "dac",
      9: "dac",
      10: "",
      11: "",
    },
    "nguHanh": "hoa"
  },
  "tangMon": {
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "dac",
      9: "dac",
      10: "",
      11: "",
    },
    "nguHanh": "mocDoiTho"
  },
  "bachHo": {
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "dac",
      9: "dac",
      10: "",
      11: "",
    },
    "nguHanh": "kim"
  },
  "thienKhoc": {
    "strengths": {
      0: "dac",
      1: "dac",
      2: "",
      3: "dac",
      4: "",
      5: "",
      6: "dac",
      7: "dac",
      8: "",
      9: "dac",
      10: "",
      11: "",
    },
    "nguHanh": "thuy"
  },
  "thienHu": {
    "strengths": {
      0: "dac",
      1: "dac",
      2: "",
      3: "dac",
      4: "",
      5: "",
      6: "dac",
      7: "dac",
      8: "",
      9: "dac",
      10: "",
      11: "",
    },
    "nguHanh": "thuy"
  },
  "thienMa": {
    "isGood": true,
    "bold": true,
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "",
      4: "",
      5: "dac",
      6: "",
      7: "",
      8: "",
      9: "",
      10: "",
      11: "",
    },
    "nguHanh": "hoa"
  },
  "thienHinh": {
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "dac",
      9: "dac",
      10: "",
      11: "",
    },
    "nguHanh": "hoa"
  },
  "thienRieu": {
    "strengths": {
      0: "",
      1: "",
      2: "dac",
      3: "dac",
      4: "",
      5: "",
      6: "",
      7: "",
      8: "",
      9: "dac",
      10: "dac",
      11: "",
    },
    "nguHanh": "thuy"
  },
  "longTri": {"isGood": true, "nguHanh": "thuy"},
  "phuongCac": {"isGood": true, "nguHanh": "mocDoiTho"},
  "tamThai": {"isGood": true, "nguHanh": "thuy"},
  "batToa": {"isGood": true, "nguHanh": "moc"},
  "anQuang": {"isGood": true, "nguHanh": "moc"},
  "thienQuy": {"isGood": true, "nguHanh": "tho"},
  "daoHoa": {"isGood": true, "nguHanh": "moc"},
  "hongLoan": {"isGood": true, "nguHanh": "thuyDoiKim"},
  "thienHi": {"isGood": true, "nguHanh": "thuy"},
  "thaiPhu": {"isGood": true, "nguHanh": "kimDoiTho"},
  "phongCao": {"isGood": true, "nguHanh": "thoDoiThuy"},
  "quocAn": {"isGood": true, "nguHanh": "tho"},
  "duongPhu": {"isGood": true, "nguHanh": "moc"},
  "thienTho": {"isGood": true, "nguHanh": "tho"},
  "bacSi": {"isGood": true, "nguHanh": "thuy"},
  "luuNienVanTinh": {"isGood": true, "nguHanh": "hoa"},
  "hoaCai": {"isGood": true, "nguHanh": "kim"},
  "thienTru": {"isGood": true, "nguHanh": "tho"},
  "thienQuan": {"isGood": true, "nguHanh": "hoa"},
  "thienPhuc": {"isGood": true, "nguHanh": "tho"},
  "thienGiai": {"isGood": true, "nguHanh": "hoa"},
  "diaGiai": {"isGood": true, "nguHanh": "tho"},
  "giaiThan": {"isGood": true, "nguHanh": "moc"},
  "thienDuc": {"isGood": true, "nguHanh": "hoa"},
  "nguyetDuc": {"isGood": true, "nguHanh": "hoa"},
  "thienY": {"isGood": true, "nguHanh": "thuy"},
  "coThan": {"nguHanh": "tho"},
  "quaTu": {"nguHanh": "tho"},
  "dauQuan": {"nguHanh": "hoa"},
  "thienThuong": {"nguHanh": "tho"},
  "thienSu": {"nguHanh": "thuy"},
  "kiepSat": {"nguHanh": "hoa"},
  "luuHa": {"nguHanh": "thuy"},
  "phaToai": {"nguHanh": "hoaDoiKim"},
  "thienTai": {"isGood": true, "nguHanh": "tho"},
  "thienLa": {"nguHanh": 'kim'},
  "diaVong": {"nguHanh": 'kim'},
  "thaiTue": {"nguHanh": "hoa"},
  "thieuDuong": {"isGood": true, "nguHanh": "hoa"},
  "thieuAm": {"isGood": true, "nguHanh": "thuy"},
  "quanPhur": {"nguHanh": "hoa"},
  "tuPhu": {"nguHanh": "hoa"},
  "trucPhu": {"nguHanh": "hoa"},
  "tuePha": {"nguHanh": "hoa"},
  "longDuc": {"isGood": true, "nguHanh": "thuy"},
  "phucDuc": {"isGood": true, "nguHanh": "tho"},
  "dieuKhach": {"nguHanh": "hoa"},
  "lucSi": {"isGood": true, "nguHanh": "hoa"},
  "thanhLong": {"isGood": true, "nguHanh": "thuy"},
  "tuongQuan": {"nguHanh": "moc"},
  "tauThu": {"isGood": true, "nguHanh": "kim"},
  "phiLiem": {"nguHanh": "hoa"},
  "hyThan": {"isGood": true, "nguHanh": "hoa"},
  "benhPhu": {"nguHanh": "thoDoiMoc"},
  "phucBinh": {"nguHanh": "hoa"},
  "quanPhuf": {"nguHanh": "hoa"},
  "truongSinh": {"isLife": true, "bold": true, "nguHanh": "thuy"},
  "mocDuc": {"isLife": true, "nguHanh": "thuy"},
  "quanDoi": {"isLife": true, "nguHanh": "kim"},
  "lamQuan": {"isLife": true, "nguHanh": "kim"},
  "deVuong": {"isLife": true, "nguHanh": "kim"},
  "suy": {"isLife": true, "nguHanh": "thuy"},
  "benh": {"isLife": true, "nguHanh": "hoa"},
  "tu": {"isLife": true, "nguHanh": "thuy"},
  "mo": {"isLife": true, "nguHanh": "tho"},
  "tuyet": {"isLife": true, "nguHanh": "tho"},
  "thai": {"isLife": true, "nguHanh": "tho"},
  "duong": {"isLife": true, "nguHanh": "moc"},
  "luuLocTon": {
    "isLuuNien": true,
    "bold": true,
    "nguHanh": "duong_thoDoiThuy",
  },
  "luuBachHo": {
    "isLuuNien": true,
    "nguHanh": "kim",
  },
  "luuDaLa": {
    "isLuuNien": true,
    "bold": true,
    "nguHanh": "am_kimDoiHoa",
  },
  "luuKinhDuong": {
    "isLuuNien": true,
    "bold": true,
    "nguHanh": "am_kimDoiHoa",
  },
  "luuTangMon": {
    "isLuuNien": true,
    "nguHanh": "mocDoiTho",
  },
  "luuThaiTue": {
    "isLuuNien": true,
    "nguHanh": "hoa",
  },
  "luuThienHu": {
    "isLuuNien": true,
    "nguHanh": "thuy",
  },
  "luuThienKhoc": {
    "isLuuNien": true,
    "nguHanh": "thuy",
  },
  "luuThienMa": {
    "isLuuNien": true,
    "bold": true,
    "nguHanh": "hoa",
  },
};
