import '../chi/chi_enum.dart';
import 'hoa_giap_enum.dart';

final hoaGiapIndexData = {
  0: {
    Chies.tys.index: HoaGiaps.haiTrungKim.index,
    Chies.tuat.index: HoaGiaps.sonDauHoa.index,
    Chies.than.index: HoaGiaps.tuyenTrungThuy.index,
    Chies.ngo.index: HoaGiaps.saTrungKim.index,
    Chies.thin.index: HoaGiaps.phuDangHoa.index,
    Chies.dan.index: HoaGiaps.daiKheThuy.index,
  },
  1: {
    Chies.suu.index: HoaGiaps.haiTrungKim.index,
    Chies.hoi.index: HoaGiaps.sonDauHoa.index,
    Chies.dau.index: HoaGiaps.tuyenTrungThuy.index,
    Chies.mui.index: HoaGiaps.saTrungKim.index,
    Chies.tyj.index: HoaGiaps.phuDangHoa.index,
    Chies.mao.index: HoaGiaps.daiKheThuy.index,
  },
  2: {
    Chies.dan.index: HoaGiaps.loTrungHoa.index,
    Chies.tys.index: HoaGiaps.gianHaThuy.index,
    Chies.tuat.index: HoaGiaps.ocThuongTho.index,
    Chies.than.index: HoaGiaps.sonHaHoa.index,
    Chies.ngo.index: HoaGiaps.thienHaThuy.index,
    Chies.thin.index: HoaGiaps.saTrungTho.index,
  },
  3: {
    Chies.mao.index: HoaGiaps.loTrungHoa.index,
    Chies.suu.index: HoaGiaps.gianHaThuy.index,
    Chies.hoi.index: HoaGiaps.ocThuongTho.index,
    Chies.dau.index: HoaGiaps.sonHaHoa.index,
    Chies.mui.index: HoaGiaps.thienHaThuy.index,
    Chies.tyj.index: HoaGiaps.saTrungTho.index,
  },
  4: {
    Chies.thin.index: HoaGiaps.daiLamMoc.index,
    Chies.dan.index: HoaGiaps.thanhDauTho.index,
    Chies.tys.index: HoaGiaps.tichLichHoa.index,
    Chies.tuat.index: HoaGiaps.binhDiaMoc.index,
    Chies.than.index: HoaGiaps.daiDichTho.index,
    Chies.ngo.index: HoaGiaps.thienThuongHoa.index,
  },
  5: {
    Chies.tyj.index: HoaGiaps.daiLamMoc.index,
    Chies.mao.index: HoaGiaps.thanhDauTho.index,
    Chies.suu.index: HoaGiaps.tichLichHoa.index,
    Chies.hoi.index: HoaGiaps.binhDiaMoc.index,
    Chies.dau.index: HoaGiaps.daiDichTho.index,
    Chies.mui.index: HoaGiaps.thienThuongHoa.index,
  },
  6: {
    Chies.ngo.index: HoaGiaps.loBangTho.index,
    Chies.thin.index: HoaGiaps.bachLapKim.index,
    Chies.dan.index: HoaGiaps.tungBachMoc.index,
    Chies.tys.index: HoaGiaps.bichThuongTho.index,
    Chies.tuat.index: HoaGiaps.thoaXuyenKim.index,
    Chies.than.index: HoaGiaps.bachLuuMoc.index,
  },
  7: {
    Chies.mui.index: HoaGiaps.loBangTho.index,
    Chies.tyj.index: HoaGiaps.bachLapKim.index,
    Chies.mao.index: HoaGiaps.tungBachMoc.index,
    Chies.suu.index: HoaGiaps.bichThuongTho.index,
    Chies.hoi.index: HoaGiaps.thoaXuyenKim.index,
    Chies.dau.index: HoaGiaps.bachLuuMoc.index,
  },
  8: {
    Chies.than.index: HoaGiaps.kiemPhongKim.index,
    Chies.ngo.index: HoaGiaps.duongLieuMoc.index,
    Chies.thin.index: HoaGiaps.truongLuuThuy.index,
    Chies.dan.index: HoaGiaps.kimBachKim.index,
    Chies.tys.index: HoaGiaps.tangChaMoc.index,
    Chies.tuat.index: HoaGiaps.daiHaiThuy.index,
  },
  9: {
    Chies.dau.index: HoaGiaps.kiemPhongKim.index,
    Chies.mui.index: HoaGiaps.duongLieuMoc.index,
    Chies.tyj.index: HoaGiaps.truongLuuThuy.index,
    Chies.mao.index: HoaGiaps.kimBachKim.index,
    Chies.suu.index: HoaGiaps.tangChaMoc.index,
    Chies.hoi.index: HoaGiaps.daiHaiThuy.index,
  },
};
