name: sunoom
description: Lunisolar calendar library.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  tauari_date_format:
    path: ../tauari_date_format
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
