name: tuvi_admin_presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  storage_options:
    path: ../storage_options
  tauari_data_core:
    path: ../tauari_data_core
  tauari_auth:
    path: ../tauari_auth
  tauari_auth_widget:
    path: ../tauari_auth_widget
  tauari_translate:
    path: ../tauari_translate
  tauari_ui:
    path: ../tauari_ui
  tauari_list_view:
    path: ../tauari_list_view
  tauari_sort:
    path: ../tauari_sort
  
  tuvi_style:
    path: ../tuvi_style
  
  lasotuvi_style:
    path: ../lasotuvi_style
  lasotuvi_domain:
    path: ../lasotuvi_domain
  lasotuvi_request:
    path: ../lasotuvi_request
  lasotuvi_commentary:
    path: ../lasotuvi_commentary
  lasotuvi_provider:
    path: ../lasotuvi_provider
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
