final amDuongNguHanhData = {
  -1: {
    'index': -1,
    'name': '-',
    'amDuong': -1,
    'nguHanh': -1,
  },
  0: {
    'index': 0,
    'name': 'am_thuy',
    'amDuong': 0,
    'nguHanh': 0,
  },
  1: {
    'index': 1,
    'name': 'duong_thuy',
    'amDuong': 1,
    'nguHanh': 0,
  },
  2: {
    'index': 2,
    'name': 'am_moc',
    'amDuong': 0,
    'nguHanh': 1,
  },
  3: {
    'index': 3,
    'name': 'duong_moc',
    'amDuong': 1,
    'nguHanh': 1,
  },
  4: {
    'index': 4,
    'name': 'am_kim',
    'amDuong': 0,
    'nguHanh': 2,
  },
  5: {
    'index': 5,
    'name': 'duong_kim',
    'amDuong': 1,
    'nguHanh': 2,
  },
  6: {
    'index': 6,
    'name': 'am_tho',
    'amDuong': 0,
    'nguHanh': 3,
  },
  7: {
    'index': 7,
    'name': 'duong_tho',
    'amDuong': 1,
    'nguHanh': 3,
  },
  8: {
    'index': 8,
    'name': 'am_hoa',
    'amDuong': 0,
    'nguHanh': 4,
  },
  9: {
    'index': 9,
    'name': 'duong_hoa',
    'amDuong': 1,
    'nguHanh': 4,
  },
  10: {
    'index': 10,
    'name': 'am_thuyDoiMoc',
    'amDuong': 0,
    'nguHanh': 5,
  },
  11: {
    'index': 11,
    'name': 'am_thuyDoiKim',
    'amDuong': 0,
    'nguHanh': 6,
  },
  12: {
    'index': 12,
    'name': 'am_thuyDoiTho',
    'amDuong': 0,
    'nguHanh': 7,
  },
  13: {
    'index': 13,
    'name': 'am_thuyDoiHoa',
    'amDuong': 0,
    'nguHanh': 8,
  },
  14: {
    'index': 14,
    'name': 'duong_thuyDoiMoc',
    'amDuong': 1,
    'nguHanh': 5,
  },
  15: {
    'index': 15,
    'name': 'duong_thuyDoiKim',
    'amDuong': 1,
    'nguHanh': 6,
  },
  16: {
    'index': 16,
    'name': 'duong_thuyDoiTho',
    'amDuong': 1,
    'nguHanh': 7,
  },
  17: {
    'index': 17,
    'name': 'duong_thuyDoiHoa',
    'amDuong': 1,
    'nguHanh': 8,
  },
  18: {
    'index': 18,
    'name': 'am_mocDoiThuy',
    'amDuong': 0,
    'nguHanh': 9,
  },
  19: {
    'index': 19,
    'name': 'am_mocDoiKim',
    'amDuong': 0,
    'nguHanh': 10,
  },
  20: {
    'index': 20,
    'name': 'am_mocDoiTho',
    'amDuong': 0,
    'nguHanh': 11,
  },
  21: {
    'index': 21,
    'name': 'am_mocDoiHoa',
    'amDuong': 0,
    'nguHanh': 12,
  },
  22: {
    'index': 22,
    'name': 'duong_mocDoiThuy',
    'amDuong': 1,
    'nguHanh': 9,
  },
  23: {
    'index': 23,
    'name': 'duong_mocDoiKim',
    'amDuong': 1,
    'nguHanh': 10,
  },
  24: {
    'index': 24,
    'name': 'duong_mocDoiTho',
    'amDuong': 1,
    'nguHanh': 11,
  },
  25: {
    'index': 25,
    'name': 'duong_mocDoiHoa',
    'amDuong': 1,
    'nguHanh': 12,
  },
  26: {
    'index': 26,
    'name': 'am_kimDoiThuy',
    'amDuong': 0,
    'nguHanh': 13,
  },
  27: {
    'index': 27,
    'name': 'am_kimDoiMoc',
    'amDuong': 0,
    'nguHanh': 14,
  },
  28: {
    'index': 28,
    'name': 'am_kimDoiTho',
    'amDuong': 0,
    'nguHanh': 15,
  },
  29: {
    'index': 29,
    'name': 'am_kimDoiHoa',
    'amDuong': 0,
    'nguHanh': 16,
  },
  30: {
    'index': 30,
    'name': 'duong_kimDoiThuy',
    'amDuong': 1,
    'nguHanh': 13,
  },
  31: {
    'index': 31,
    'name': 'duong_kimDoimoc',
    'amDuong': 1,
    'nguHanh': 14,
  },
  32: {
    'index': 32,
    'name': 'duong_kimDoiTho',
    'amDuong': 1,
    'nguHanh': 15,
  },
  33: {
    'index': 33,
    'name': 'duong_kimDoiHoa',
    'amDuong': 1,
    'nguHanh': 16,
  },
  34: {
    'index': 34,
    'name': 'am_thoDoiThuy',
    'amDuong': 0,
    'nguHanh': 17,
  },
  35: {
    'index': 35,
    'name': 'am_thoDoiMoc',
    'amDuong': 0,
    'nguHanh': 18,
  },
  36: {
    'index': 36,
    'name': 'am_thoDoiKim',
    'amDuong': 0,
    'nguHanh': 19,
  },
  37: {
    'index': 37,
    'name': 'am_thoDoiHoa',
    'amDuong': 0,
    'nguHanh': 20,
  },
  38: {
    'index': 38,
    'name': 'duong_thoDoiThuy',
    'amDuong': 1,
    'nguHanh': 17,
  },
  39: {
    'index': 39,
    'name': 'duong_thoDoimoc',
    'amDuong': 1,
    'nguHanh': 18,
  },
  40: {
    'index': 40,
    'name': 'duong_thoDoiKim',
    'amDuong': 1,
    'nguHanh': 19,
  },
  41: {
    'index': 41,
    'name': 'duong_thoDoiHoa',
    'amDuong': 1,
    'nguHanh': 20,
  },
  42: {
    'index': 42,
    'name': 'am_hoaDoiThuy',
    'amDuong': 0,
    'nguHanh': 21,
  },
  43: {
    'index': 43,
    'name': 'am_hoaDoiMoc',
    'amDuong': 0,
    'nguHanh': 22,
  },
  44: {
    'index': 44,
    'name': 'am_hoaDoiKim',
    'amDuong': 0,
    'nguHanh': 23,
  },
  45: {
    'index': 45,
    'name': 'am_hoaDoiTho',
    'amDuong': 0,
    'nguHanh': 24,
  },
  46: {
    'index': 46,
    'name': 'duong_hoaDoiThuy',
    'amDuong': 1,
    'nguHanh': 21,
  },
  47: {
    'index': 47,
    'name': 'duong_hoaDoimoc',
    'amDuong': 1,
    'nguHanh': 22,
  },
  48: {
    'index': 48,
    'name': 'duong_hoaDoiKim',
    'amDuong': 1,
    'nguHanh': 23,
  },
  49: {
    'index': 49,
    'name': 'duong_hoaDoiTho',
    'amDuong': 1,
    'nguHanh': 24,
  },
  50: {
    'index': 50,
    'name': 'thuyDoiMoc',
    'amDuong': -1,
    'nguHanh': 5,
  },
  51: {
    'index': 51,
    'name': 'thuyDoiKim',
    'amDuong': -1,
    'nguHanh': 6,
  },
  52: {
    'index': 52,
    'name': 'thuyDoiTho',
    'amDuong': -1,
    'nguHanh': 7,
  },
  53: {
    'index': 53,
    'name': 'thuyDoiHoa',
    'amDuong': -1,
    'nguHanh': 8,
  },
  54: {
    'index': 54,
    'name': 'mocDoiThuy',
    'amDuong': -1,
    'nguHanh': 9,
  },
  55: {
    'index': 55,
    'name': 'mocDoiKim',
    'amDuong': -1,
    'nguHanh': 10,
  },
  56: {
    'index': 56,
    'name': 'mocDoiTho',
    'amDuong': -1,
    'nguHanh': 11,
  },
  57: {
    'index': 57,
    'name': 'mocDoiHoa',
    'amDuong': -1,
    'nguHanh': 12,
  },
  58: {
    'index': 58,
    'name': 'kimDoiThuy',
    'amDuong': -1,
    'nguHanh': 13,
  },
  59: {
    'index': 59,
    'name': 'kimDoiMoc',
    'amDuong': -1,
    'nguHanh': 14,
  },
  60: {
    'index': 60,
    'name': 'kimDoiTho',
    'amDuong': -1,
    'nguHanh': 15,
  },
  61: {
    'index': 61,
    'name': 'kimDoiHoa',
    'amDuong': -1,
    'nguHanh': 16,
  },
  62: {
    'index': 62,
    'name': 'thoDoiThuy',
    'amDuong': -1,
    'nguHanh': 17,
  },
  63: {
    'index': 63,
    'name': 'thoDoiKim',
    'amDuong': -1,
    'nguHanh': 18,
  },
  64: {
    'index': 64,
    'name': 'thoDoiMoc',
    'amDuong': -1,
    'nguHanh': 19,
  },
  65: {
    'index': 65,
    'name': 'thoDoiHoa',
    'amDuong': -1,
    'nguHanh': 20,
  },
  66: {
    'index': 66,
    'name': 'hoaDoiThuy',
    'amDuong': -1,
    'nguHanh': 21,
  },
  67: {
    'index': 67,
    'name': 'hoaDoiKim',
    'amDuong': -1,
    'nguHanh': 22,
  },
  68: {
    'index': 68,
    'name': 'hoaDoiMoc',
    'amDuong': -1,
    'nguHanh': 23,
  },
  69: {
    'index': 69,
    'name': 'hoaDoiTho',
    'amDuong': -1,
    'nguHanh': 24,
  },
  70: {
    'index': 70,
    'name': 'thuy',
    'amDuong': -1,
    'nguHanh': 0,
  },
  71: {
    'index': 71,
    'name': 'moc',
    'amDuong': -1,
    'nguHanh': 1,
  },
  72: {
    'index': 72,
    'name': 'kim',
    'amDuong': -1,
    'nguHanh': 2,
  },
  73: {
    'index': 73,
    'name': 'tho',
    'amDuong': -1,
    'nguHanh': 3,
  },
  74: {
    'index': 74,
    'name': 'hoa',
    'amDuong': -1,
    'nguHanh': 4,
  },
};
